name = "Wildfire"
prefix = "wildfire"
author = "Seb"
template = "cba"
mainprefix = "z"
include = ["./include"]
files = [
    "mod.cpp",
    "logo.paa",
    "logoSmall.paa",
    "logoOver.paa"
] 
folder_optionals = true
sig_version = 3